import argparse
import csv
import json
from pathlib import Path

import numpy as np


def _prepare_array(arr: np.ndarray, frames: int, channels: int, stride: int) -> np.ndarray:
    if arr.ndim != 2:
        raise ValueError(f"Expected 2D array, got shape {arr.shape}")
    if stride <= 0:
        raise ValueError("stride must be > 0")
    sampled = arr[::stride]
    if sampled.shape[0] < frames:
        raise ValueError(f"Not enough frames after stride: requested={frames}, available={sampled.shape[0]}")
    if channels <= 0 or channels > sampled.shape[1]:
        raise ValueError(f"channels must be in [1, {sampled.shape[1]}]")
    return np.asarray(sampled[:frames, :channels], dtype=np.float64)


def _write_csv(path: Path, arr: np.ndarray, start_timestamp_ms: int, step_ms: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["timestamp_ms"] + [f"s{i}" for i in range(arr.shape[1])])
        ts = int(start_timestamp_ms)
        for row in arr:
            writer.writerow([ts] + [f"{x:.8f}" for x in row.tolist()])
            ts += int(step_ms)


def _quantize_int16(arr: np.ndarray):
    offsets = arr.mean(axis=0)
    half_ranges = np.max(np.abs(arr - offsets), axis=0)
    half_ranges = np.where(half_ranges < 1e-9, 1e-9, half_ranges)
    scales = half_ranges / 32767.0
    q = np.round((arr - offsets) / scales).astype(np.int16)
    return q, offsets, scales


def _write_header(path: Path, q: np.ndarray, offsets: np.ndarray, scales: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n")
        f.write("#include <pgmspace.h>\n\n")
        f.write("// Generated by scripts/export_esp32_replay.py\n")
        f.write(f"static const int ESP32_REPLAY_FRAMES = {q.shape[0]};\n")
        f.write(f"static const int ESP32_REPLAY_CHANNELS = {q.shape[1]};\n\n")

        f.write("static const float ESP32_REPLAY_OFFSETS[] PROGMEM = {\n")
        f.write(",\n".join("  " + ", ".join(f"{x:.10f}f" for x in offsets[i:i + 8]) for i in range(0, len(offsets), 8)))
        f.write("\n};\n\n")

        f.write("static const float ESP32_REPLAY_SCALES[] PROGMEM = {\n")
        f.write(",\n".join("  " + ", ".join(f"{x:.10f}f" for x in scales[i:i + 8]) for i in range(0, len(scales), 8)))
        f.write("\n};\n\n")

        f.write("static const int16_t ESP32_REPLAY_DATA[][ESP32_REPLAY_CHANNELS] PROGMEM = {\n")
        for i, row in enumerate(q):
            suffix = "," if i < (q.shape[0] - 1) else ""
            f.write("  {" + ", ".join(str(int(v)) for v in row.tolist()) + "}" + suffix + "\n")
        f.write("};\n\n")

        f.write("// Dequantization on ESP32:\n")
        f.write("// value = ESP32_REPLAY_DATA[frame][ch] * ESP32_REPLAY_SCALES[ch] + ESP32_REPLAY_OFFSETS[ch]\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export synthetic replay data for ESP32 firmware")
    parser.add_argument("--input", default="processed/synthetic/test.npy", help="Input .npy file path")
    parser.add_argument("--frames", type=int, default=256, help="Number of frames to export")
    parser.add_argument("--channels", type=int, default=64, help="Number of channels to export")
    parser.add_argument("--stride", type=int, default=1, help="Sample every Nth frame")
    parser.add_argument("--start-timestamp-ms", type=int, default=1710000000000)
    parser.add_argument("--step-ms", type=int, default=500)
    parser.add_argument("--csv-out", default="data/synthetic/esp32_replay.csv")
    parser.add_argument("--header-out", default="data/synthetic/esp32_replay.h")
    parser.add_argument("--meta-out", default="data/synthetic/esp32_replay_meta.json")
    parser.add_argument("--skip-csv", action="store_true")
    parser.add_argument("--skip-header", action="store_true")
    args = parser.parse_args()

    arr = np.load(args.input)
    prepared = _prepare_array(arr, frames=args.frames, channels=args.channels, stride=args.stride)

    if not args.skip_csv:
        _write_csv(Path(args.csv_out), prepared, args.start_timestamp_ms, args.step_ms)

    q, offsets, scales = _quantize_int16(prepared)
    if not args.skip_header:
        _write_header(Path(args.header_out), q, offsets, scales)

    meta = {
        "input": str(args.input),
        "frames": int(prepared.shape[0]),
        "channels": int(prepared.shape[1]),
        "stride": int(args.stride),
        "start_timestamp_ms": int(args.start_timestamp_ms),
        "step_ms": int(args.step_ms),
        "csv_out": str(args.csv_out),
        "header_out": str(args.header_out),
        "quantization": "int16_affine_centered",
    }
    meta_path = Path(args.meta_out)
    meta_path.parent.mkdir(parents=True, exist_ok=True)
    meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")

    print(
        f"Export complete: frames={prepared.shape[0]}, channels={prepared.shape[1]}, "
        f"csv={args.csv_out if not args.skip_csv else 'skipped'}, "
        f"header={args.header_out if not args.skip_header else 'skipped'}"
    )


if __name__ == "__main__":
    main()
